-- Migration: Add archived_at fields to categories and subcategories
-- Fixes inconsistency between TypeScript types and Supabase schema
-- Generated by Technical Audit Report

-- Add archived_at to categories table
ALTER TABLE public.categories 
ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE NULL;

-- Add archived_at to subcategories table
ALTER TABLE public.subcategories 
ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE NULL;

-- Add index for better query performance when filtering by archived status
CREATE INDEX IF NOT EXISTS idx_categories_archived_at 
ON public.categories(archived_at) 
WHERE archived_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_subcategories_archived_at 
ON public.subcategories(archived_at) 
WHERE archived_at IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN public.categories.archived_at IS 'Timestamp when category was archived. NULL means active.';
COMMENT ON COLUMN public.subcategories.archived_at IS 'Timestamp when subcategory was archived. NULL means active.';
